Repository apytypes/apytypes, pull requests merged in 2024-06, with the labels that each got.

#459 Improve documentation
  docs/_static/liu-white.svg
  docs/development.rst
  docs/index.rst
  pyproject.toml
Labels: documentation

#460 Add black LiU-image for light mode in documentation
  docs/_static/liu-black.svg
  docs/index.rst
Labels: documentation

#472 Bump CIBW to 2.19
  .github/workflows/publish-test-pypi.yml
Labels: CI: Run cibuildwheel

#475 ci: build and publish source distribution
  .github/workflows/publish-test-pypi.yml
  CHANGELOG.md
Labels: CI: Run cibuildwheel

#473 Added Sum,NanSum, CumSum and NanCumSum
  CHANGELOG.md
  lib/apytypes/_apytypes.pyi
  lib/test/apyfixedarray/test_methods.py
  lib/test/apyfloatarray/test_methods.py
  src/apyfixedarray.cc
  src/apyfixedarray.h
  src/apyfixedarray_wrapper.cc
  src/apyfloatarray.cc
  src/apyfloatarray.h
  src/apyfloatarray_wrapper.cc
  src/apytypes_util.h
Labels: enhancement, Arrays
