Repository apytypes/apytypes, pull requests merged in 2024-09, with the labels that each got.

#474 ci: revert to windows-latest runner
  .github/workflows/publish-test-pypi.yml
  .github/workflows/tests.yml
  src/python_util.h
Labels: CI: Run cibuildwheel

#493 Documentation fixes
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  docs/api/apyfixedarray.rst
  docs/api/apyfloatarray.rst
  docs/api/arrayfunctions.rst
  pyproject.toml
  src/apyfixedarray_wrapper.cc
  src/apyfloatarray_wrapper.cc
Labels: documentation

#500 Add APyFloatArray.to_bits()
  CHANGELOG.md
  docs/api/apyfloatarray.rst
  lib/test/apyfloatarray/test_methods.py
  src/apyfixedarray.h
  src/apyfloat.cc
  src/apyfloat_util.h
  src/apyfloatarray.cc
  src/apyfloatarray.h
  src/apyfloatarray_wrapper.cc
Labels: enhancement, APyFloat, Arrays

#502 Add `APyFloatArray.__getitem__`: `int`, `slice`, `ellipsis`, and `tuple`
  lib/apytypes/_apytypes.pyi
  lib/test/apyfloatarray/test_get_item.py
  lib/test/apyfloatarray/test_methods.py
  src/apyfloatarray.cc
  src/apyfloatarray.h
  src/apyfloatarray_iterator.cc
Labels: APyFloat, Arrays

#503 ci: fix publish workflow [2]
  .github/workflows/publish-test-pypi.yml
Labels: CI: Run cibuildwheel

#513 Improve `arange`
  CHANGELOG.md
  lib/apytypes/_apytypes.pyi
  lib/apytypes/_array_functions.py
  lib/apytypes/_array_functions.pyi
  lib/test/test_array_functions.py
  src/apyfixed.cc
  src/apyfixed.h
  src/apyfixedarray.cc
  src/apyfixedarray.h
  src/apyfixedarray_wrapper.cc
  src/apyfloat.cc
  src/apyfloat.h
  src/apyfloatarray.cc
  src/apyfloatarray.h
  src/apyfloatarray_wrapper.cc
  src/apytypes_util.h
  src/array_utils.h
Labels: Arrays

#528 Add `APyFloatArray.from_bits`
  CHANGELOG.md
  lib/apytypes/_apytypes.pyi
  lib/test/apyfloatarray/test_methods.py
  src/apyfloat.cc
  src/apyfloat.h
  src/apyfloatarray.cc
  src/apyfloatarray.h
  src/apyfloatarray_wrapper.cc
Labels: enhancement, APyFloat, Arrays
