Repository apytypes/apytypes, pull requests merged in 2025-09, with the labels that each got.

#773 Always fetch tags during checkout
  .github/workflows/codeql.yml
  .github/workflows/documentation.yml
  .github/workflows/publish-test-pypi.yml
  .github/workflows/run_coverage.yml
  .github/workflows/stub-and-doctests.yml
  .github/workflows/tests-32-bits.yml
  .github/workflows/tests-cocotb.yml
  .github/workflows/tests-debug-memcheck.yml
  .github/workflows/tests-min-deps.yml
  .github/workflows/tests.yml
Labels: CI: Run cibuildwheel

#772 Add array creation method `meshgrid`
  CHANGELOG.md
  docs/api/arrayfunctions.rst
  lib/apytypes/__init__.py
  lib/apytypes/_array_functions.py
  lib/test/test_array_functions.py
  src/apyarray.h
  src/apycfixedarray_wrapper.cc
  src/apycfloatarray_wrapper.cc
  src/apyfixedarray_wrapper.cc
  src/apyfloatarray_wrapper.cc
Labels: enhancement, Arrays

#776 Add example for approximate floating-point multiplication
  examples/approximate_multiplication.py
  examples/ode_solver.py
Labels: documentation, APyFloat

#778 Handle dtype and copy arguments in __array__
  CHANGELOG.md
  examples/approximate_multiplication.py
  lib/apytypes/_apytypes.pyi
  lib/test/apyfixedarray/test_methods.py
  lib/test/apyfloatarray/test_methods.py
  src/apyarray.h
  src/apycfixedarray.cc
  src/apycfixedarray.h
  src/apycfixedarray_wrapper.cc
  src/apycfloatarray.cc
  src/apycfloatarray.h
  src/apycfloatarray_wrapper.cc
  src/apyfixedarray.cc
  src/apyfixedarray.h
  src/apyfixedarray_wrapper.cc
  src/apyfloatarray.cc
  src/apyfloatarray.h
  src/apyfloatarray_wrapper.cc
Labels: enhancement, Arrays

#781 APyTypes v0.4.0 release commit
  CHANGELOG.md
Labels: CI: Run cibuildwheel
