Repository apytypes/apytypes, pull requests merged in 2025-02, with the labels that each got.

#590 Improve documentation
  docs/conf.py
  docs/index.rst
  docs/publications.rst
  pyproject.toml
Labels: documentation

#596 Add more tests for special cases
  lib/test/apyfixed/test_arithmetic.py
  lib/test/apyfixedarray/test_methods.py
Labels: test

#600 Improve argument handling in `arange`
  lib/apytypes/_array_functions.py
  lib/test/test_array_functions.py
Labels: enhancement, Arrays

#594 Avoid casting Python ints to floats in APyFixedArray.from_*
  CHANGELOG.md
  lib/test/apyfixed/test_methods.py
  lib/test/apyfixedarray/test_constructors.py
  src/apycfixedarray.cc
  src/apyfixed.cc
  src/apyfixed_util.h
  src/apyfixedarray.cc
  src/apyfloat_util.h
Labels: APyFixed, quantization, Arrays

#610 Improve types in docs
  lib/apytypes/_apytypes.pyi
  lib/apytypes/_array_functions.py
  lib/apytypes/_utils.py
  lib/apytypes/vhdl.py
  src/apycfixed_wrapper.cc
  src/apycfixedarray_wrapper.cc
  src/apycfloat_wrapper.cc
  src/apyfixed_wrapper.cc
  src/apyfixedarray_wrapper.cc
  src/apyfloat_wrapper.cc
  src/apyfloatarray_wrapper.cc
  src/apytypes_wrapper.cc
Labels: documentation

#611 Fix cast example for APyFixed
  lib/apytypes/_apytypes.pyi
  src/apyfixed_wrapper.cc
Labels: documentation, APyFixed

#614 Add copy method
  CHANGELOG.md
  lib/apytypes/_apytypes.pyi
  lib/test/apycfixedarray/test_methods.py
  lib/test/apyfixedarray/test_methods.py
  lib/test/apyfloatarray/test_methods.py
  src/apycfixedarray.h
  src/apycfixedarray_wrapper.cc
  src/apyfixedarray.h
  src/apyfixedarray_wrapper.cc
  src/apyfloatarray.h
  src/apyfloatarray_wrapper.cc
Labels: enhancement

#619 Use SIMD for fixed-point array abs and negation
  CHANGELOG.md
  src/apycfixedarray.cc
  src/apyfixedarray.cc
  src/apytypes_simd.cc
  src/apytypes_simd.h
Labels: performance

#622 Simplify multi-limb negate
  src/apytypes_mp.h
  src/apytypes_util.h
Labels: performance
